package service;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.1.6
 * 2018-06-13T20:31:52.659+02:00
 * Generated source version: 3.1.6
 * 
 */
@WebService(targetNamespace = "http://www.example.org/novcanik/", name = "novcanik")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface Novcanik {

    @WebMethod(action = "http://www.example.org/novcanik/stanje")
    @WebResult(name = "out", targetNamespace = "", partName = "out")
    public double stanje();

    @WebMethod
    @WebResult(name = "out", targetNamespace = "", partName = "out")
    public boolean skiniSaNovcanika(
        @WebParam(partName = "in", name = "in", targetNamespace = "")
        double in
    );

    @WebMethod
    @WebResult(name = "out", targetNamespace = "", partName = "out")
    public boolean dodajNaNavcanik(
        @WebParam(partName = "in", name = "in", targetNamespace = "")
        double in
    );
}
